notifications:
  email: false

language: python

python:
  - "2.7"

addons:
  postgresql: "11.2"

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libspatialite5 libspatialite-dev
    - sudo apt-get install -y python-software-properties
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
    - sudo apt-get update -qq
    - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
    - sudo apt-get update
    - sudo apt-get install -y postgresql-client-11
    - sudo apt-get install -y libgssapi-krb5-2
    - sudo apt-get install -y libicu60
    - sudo apt-get install -y libllvm6.0
    - sudo apt-get install -y libssl1.1
    - sudo apt-get install -y libstdc++6
    - sudo apt-get install -y libsystemd0

    - sudo apt-get install -y postgresql-11
    - sudo apt-get install -y libgdal20
    - sudo apt-get install -y libgeos-c1v5
    - sudo apt-get install -y libjson-c3
    - sudo apt-get install -y liblwgeom-2.5-0
    - sudo apt-get install -y libproj12
    - sudo apt-get install -y libprotobuf-c1
    - sudo apt-get install -y libsfcgal1
    - sudo apt-get install -y postgresql-11-postgis-2.5-scripts
    - sudo apt-get install -y postgresql-11-postgis-2.5
    - sudo apt-get install -y gdal-bin libgdal-dev
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal

before_script:
    - psql -U postgres -c "create extension postgis"
    - createuser hot --superuser --createdb -U postgres

install:
    "pip install -r requirements-dev.txt"

# command to run tests
script:
    ./manage.py test


